# Generated by Django 3.2 on 2022-07-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thum', models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_thum/')),
                ('title_img', models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_title/')),
                ('poster', models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_poster/')),
                ('time', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('포엠학원 북구캠퍼스', '북구점'), ('포엠학원 지곡캠퍼스', '지곡점'), ('포엠학원 센텀캠퍼스', '센텀점')], max_length=100)),
                ('is_opened', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='presentationapp.presentation')),
            ],
        ),
    ]
