# Generated by Django 3.2 on 2022-07-18 08:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='place',
            field=models.CharField(choices=[('포엠학원 지곡캠퍼스', '지곡점'), ('포엠학원 북구캠퍼스', '북구점'), ('포엠학원 센텀캠퍼스', '센텀점')], max_length=100),
        ),
        migrations.CreateModel(
            name='PresentationApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=10)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='presentationapp.presentation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='presentationapply',
            constraint=models.UniqueConstraint(fields=('presentation', 'phone_num'), name='unique_apply'),
        ),
    ]
