# Generated by Django 3.2 on 2022-07-18 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0002_auto_20220718_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationapply',
            name='phone_num',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
