# Generated by Django 3.2 on 2022-07-19 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0003_alter_presentationapply_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='place',
            field=models.CharField(choices=[('포엠학원 센텀캠퍼스', '센텀점'), ('포엠학원 지곡캠퍼스', '지곡점'), ('포엠학원 북구캠퍼스', '북구점')], max_length=100),
        ),
        migrations.AlterField(
            model_name='presentationapply',
            name='phone_num',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
