# Generated by Django 3.2 on 2022-07-19 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0005_auto_20220719_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationapply',
            name='phone_num',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
