# Generated by Django 3.2 on 2022-07-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0006_alter_presentationapply_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationapply',
            name='phone_num',
            field=models.CharField(max_length=13),
        ),
    ]
