# Generated by Django 3.2 on 2022-07-19 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presentationapp', '0009_alter_presentation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationapply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentation',
            name='place',
            field=models.CharField(choices=[('포엠학원 북구캠퍼스', '북구점'), ('포엠학원 지곡캠퍼스', '지곡점'), ('포엠학원 센텀캠퍼스', '센텀점')], max_length=100),
        ),
    ]
