# Generated by Django 3.2 on 2022-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='post/no_image.png', null=True, upload_to='post/')),
                ('url', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation/')),
                ('time', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='teacher/no_image_man.png', null=True, upload_to='teacher/')),
                ('poster', models.ImageField(default='poster/no_image_man.png', null=True, upload_to='poster/')),
                ('subject', models.CharField(choices=[('kor', '국어'), ('math', '수학'), ('eng', '영어'), ('sci', '과학'), ('ess', '논술')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_activated', models.BooleanField(default=True)),
            ],
        ),
    ]
