# Generated by Django 3.2 on 2022-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20220708_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='image',
        ),
        migrations.AddField(
            model_name='presentation',
            name='poster',
            field=models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_poster/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='thum',
            field=models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_thum/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='title_img',
            field=models.ImageField(default='presentation/no_image.png', null=True, upload_to='presentation_title/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='place',
            field=models.CharField(choices=[('포엠학원 북구캠퍼스', '북구점'), ('포엠학원 센텀캠퍼스', '센텀점'), ('포엠학원 지곡캠퍼스', '지곡점')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.CharField(choices=[('포엠학원 북구캠퍼스', '북구점'), ('포엠학원 센텀캠퍼스', '센텀점'), ('포엠학원 지곡캠퍼스', '지곡점')], max_length=20),
        ),
    ]
